version: "2"
services:
  vsftpd:
    image: cusdeb/vsftpd:3.0.3-amd64
    environment:
    - PORT=${PORT}
    - USERNAME=${USERNAME}
    - PASSWORD=${PASSWORD}
    network_mode: "host"
    volumes:
    - /srv/ftp:/ftp

