version: "2"
services:
  vsftpd:
    image: cusdeb.com:5000/vsftpd:3_0_3_armhf
    command: /usr/bin/run.sh
    environment:
    - PORT=8004
    - USERNAME=cusdeb
    - PASSWORD=cusdeb
    network_mode: "host"
    volumes:
    - /srv/common/downloads:/ftp

