language: bash

addons:
  apt:
    sources:
    - debian-sid

install:
  - sudo apt-get install -y --allow-unauthenticated shellcheck

script:
  - bash -c 'shellcheck mediawiki/*.sh'
  - bash -c 'shellcheck parsoid/docker-entrypoint.sh'
  - bash -c 'shellcheck rocketchat/docker-entrypoint.sh'
  - bash -c 'shellcheck transmission-web/docker-entrypoint.sh'
