matrix:
  include:
    - language: bash

      addons:
        apt:
          sources:
          - debian-sid

      before_install:
        - sudo apt-get install -y cabal-install shunit2
        - cabal update
        - cabal install shellcheck

      script:
        - bash -c 'cd baseimages && find . -type f -name "*.sh" | xargs shellcheck -x -e SC2034,SC2148'

    - language: python

      python:
        - 3.6

      services:
        - mongodb

      before_install:
        - cd hubot-bridge/

      install:
        - pip install -r requirements.txt
        - pip install pylint==2.3.1

      before_script:
        - mongo rocketchat --eval 'db.createCollection("users", { });db.users.insert([{_id:"rocket.cat",language:"ru"},{_id:"rocket.dog"}])'

      script:
        - find -name "*.py" -not -path "./venv/*" | xargs pylint
        - env PYTHONPATH=$(pwd) py.test tests/

      after_script:
        - cd ../
