language: python

python:
  - 3.8

install:
  - sudo apt-get install -y --allow-unauthenticated shellcheck
  - pip install pylint

script:
  - bash -c 'shellcheck mediawiki/*.sh'
  - bash -c 'shellcheck mwlib/docker-entrypoint.sh'
  - bash -c 'shellcheck parsoid/docker-entrypoint.sh'
  - bash -c 'shellcheck redis/docker-entrypoint.sh'
  - bash -c 'shellcheck rocketchat/docker-entrypoint.sh'
  - bash -c 'shellcheck transmission-web/docker-entrypoint.sh'
  - bash -c 'shellcheck vsftpd/docker-entrypoint.sh'
  - find -name "*.py" -not -path "./.git/*" | xargs pylint

