version: "2"
services:
  mediawiki:
    image: cusdeb/mediawiki:1.31-amd64
    environment:
    - PORT=8004
    - WG_SITENAME=My KB
    - WG_META_NAMESPACE=My_KB
    - WG_PROTOCOL=http
    - WG_SERVER=127.0.0.1:8004
    - WG_EMERGENCY_CONTACT=username@domain.com
    - WG_PASSWORD_SENDER=username@domain.com
    - WG_DB_SERVER=127.0.0.1:33061
    - WG_DB_NAME=knowledge_base
    - WG_DB_USER=root
    - WG_DB_PASSWORD=cusdeb
    - ALLOW_ACCOUNT_CREATION=true
    - ALLOW_ACCOUNT_EDITING=true
    - ALLOW_ANONYMOUS_READING=false
    - ALLOW_ANONYMOUS_EDITING=true
    # Parsoid server
    - PARSOID_DOMAIN=parsoid
    - PARSOID_HOST=http://127.0.0.1:8005
    # Render server
    - CREDENTIALS=${CREDENTIALS}
    - RENDER_SERVER_HOST=${RENDER_SERVER_HOST}
    network_mode: "host"
    volumes:
    - /srv/mediawiki/deleted:/var/www/w/deleted
    - /srv/mediawiki/images:/var/www/w/images
    - ./kblogo.png:/tmp/kblogo.png
  mariadb:
    image: cusdeb/mariadb:10.1-amd64
    network_mode: "host"
    environment:
    - MYSQLD_port=33061
    - MYSQL_ROOT_PASSWORD=cusdeb
    - MYSQL_DATABASE=
    - MYSQL_USER=
    - MYSQL_PASSWORD=
    volumes:
    - /srv/mysql:/var/lib/mysql
  parsoid:
    image: cusdeb/parsoid:0.10.0-amd64
    environment:
    - PORT=8005
    - PARSOID_DOMAIN=parsoid
    - MW_API_ENDPOINT=http://127.0.0.1:8004/api.php
    - LOGGING_LEVEL=info
    - DEBUG_MODE=false
    network_mode: "host"
  mw_qserve:
    image: cusdeb/mwlib:0.16.2
    network_mode: "host"
    environment:
    - MW_QSERVE_PORT=${MW_QSERVE_PORT}
    - TYPE=mw-qserve
  postman:
    image: cusdeb/mwlib:0.16.2
    network_mode: "host"
    environment:
    - TYPE=postman
  nserve:
    image: cusdeb/mwlib:0.16.2
    network_mode: "host"
    environment:
    - PORT=${PORT}
    - TYPE=nserve
  nslave:
    image: cusdeb/mwlib:0.16.2
    network_mode: "host"
    environment:
    - TYPE=nslave

