version: "2"
services:
  mediawiki:
    image: cusdeb/mediawiki:1.35-amd64
    environment:
    - PORT=${PORT}
    - WG_SITENAME=${WG_SITENAME}
    - WG_META_NAMESPACE=${WG_META_NAMESPACE}
    - WG_PROTOCOL=${WG_PROTOCOL}
    - WG_SERVER=${WG_SERVER}
    - WG_EMERGENCY_CONTACT=${WG_EMERGENCY_CONTACT}
    - WG_PASSWORD_SENDER=${WG_PASSWORD_SENDER}
    - WG_DB_SERVER=${WG_DB_SERVER}
    - WG_DB_NAME=${WG_DB_NAME}
    - WG_DB_USER=${WG_DB_USER}
    - WG_DB_PASSWORD=${WG_DB_PASSWORD}
    - ALLOW_ACCOUNT_CREATION=${ALLOW_ACCOUNT_CREATION}
    - ALLOW_ACCOUNT_EDITING=${ALLOW_ACCOUNT_EDITING}
    - ALLOW_ANONYMOUS_READING=${ALLOW_ANONYMOUS_READING}
    - ALLOW_ANONYMOUS_EDITING=${ALLOW_ANONYMOUS_EDITING}
    # Render server
    - CREDENTIALS=${CREDENTIALS}
    - RENDER_SERVER_HOST=${RENDER_SERVER_HOST}
    network_mode: "host"
    volumes:
    - /srv/mediawiki/deleted:/var/www/w/deleted
    - /srv/mediawiki/images:/var/www/w/images
    - ./kblogo.png:/tmp/kblogo.png
  mariadb:
    image: cusdeb/mariadb:10.1-amd64
    network_mode: "host"
    environment:
    - MYSQLD_port=33061
    - MYSQL_ROOT_PASSWORD=cusdeb
    - MYSQL_DATABASE=
    - MYSQL_USER=
    - MYSQL_PASSWORD=
    volumes:
    - /srv/mysql:/var/lib/mysql
  mw_qserve:
    image: cusdeb/mwlib:0.16.2
    network_mode: "host"
    environment:
    - MW_QSERVE_PORT=${MW_QSERVE_PORT}
    - TYPE=mw-qserve
  postman:
    image: cusdeb/mwlib:0.16.2
    network_mode: "host"
    environment:
    - TYPE=postman
  nserve:
    image: cusdeb/mwlib:0.16.2
    network_mode: "host"
    environment:
    - PORT=${PORT}
    - TYPE=nserve
  nslave:
    image: cusdeb/mwlib:0.16.2
    network_mode: "host"
    environment:
    - TYPE=nslave

