version: "2"
services:
  nextcloud:
    image: cusdeb.com:5000/nextcloud:13beta3_armhf
    command: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
    environment:
    - PORT=8001
    network_mode: "host"
    volumes:
    - /srv/nextcloud/config.php:/var/www/nc/config/config.php
    - /srv/nextcloud/data:/var/www/nc/data/
