version: "2"
services:
  rocketchat:
    image: cusdeb/rocketchat:1.1-amd64
    networks:
    - rocketchat-network
    environment:
    - PORT=8006
    - MONGO_DATABASE=rocketchat
    - MONGO_HOST=mongo:27017
    - MONGO_OPLOG_HOST=mongo:27017
    - ROOT_URL=http://127.0.0.1:8006
    ports:
    - "8006:8006"
  mongo:
    image: mongo:3.4-jessie
    networks:
    - rocketchat-network
    volumes:
    - /srv/mongo:/data/db
    command: mongod --oplogSize 128 --replSet rs0
networks:
  rocketchat-network:
    driver: bridge
