version: "2"
services:
  mariadb:
    image: cusdeb/mariadb:10.1.28-armhf
    network_mode: "host"
    environment:
    - MYSQL_ROOT_PASSWORD=cusdeb
    - MYSQL_DATABASE=
    - MYSQL_USER=
    - MYSQL_PASSWORD=
    volumes:
    - /srv/mysql:/var/lib/mysql
