version: "2"
services:
  transmission-web:
    image: cusdeb/transmission:2.94-amd64
    command: /entrypoint.sh
    environment:
    - ALLOWED=192.168.*.*
    - AUTH=true
    - LOGIN=cusdeb
    - PASSWORD=cusdeb
    - PORT=8003
    network_mode: "host"
    volumes:
    - /srv/common/downloads:/root/Downloads

