version: "2"
services:
  transmission-web:
    image: cusdeb/transmission:2.94-amd64
    environment:
    - ALLOWED=${ALLOWED}
    - AUTH=${AUTH}
    - LOGIN=${LOGIN}
    - PASSWORD=${PASSWORD}
    - PORT=${PORT}
    network_mode: "host"
    volumes:
    - /srv/common/downloads:/root/Downloads

