version: "2"
services:
  hubot-rocketchat:
    image: cusdeb/hubot-rocketchat:2.0-armhf
    network_mode: "host"
    environment:
    - EXTERNAL_SCRIPTS=${EXTERNAL_SCRIPTS}
    - HUBOT_NAME=${HUBOT_NAME}
    - LISTEN_ON_ALL_PUBLIC=${LISTEN_ON_ALL_PUBLIC}
    - RESPOND_TO_DM=${RESPOND_TO_DM}
    - ROCKETCHAT_PASSWORD=${ROCKETCHAT_PASSWORD}
    - ROCKETCHAT_ROOM=${ROCKETCHAT_ROOM}
    - ROCKETCHAT_URL=${ROCKETCHAT_URL}
    - ROCKETCHAT_USER=${ROCKETCHAT_USER}
    - TZ=${TZ}
    # hubot-happy-birthder
    - ANNOUNCER_CRON_STRING=${ANNOUNCER_CRON_STRING}
    - BIRTHDAY_ANNOUNCEMENT_BEFORE_CNT=${BIRTHDAY_ANNOUNCEMENT_BEFORE_CNT}
    - BIRTHDAY_CHANNEL_BLACKLIST=${BIRTHDAY_CHANNEL_BLACKLIST}
    - BIRTHDAY_CHANNEL_MESSAGE=${BIRTHDAY_CHANNEL_MESSAGE}
    - BIRTHDAY_CRON_STRING=${BIRTHDAY_CRON_STRING}
    - BIRTHDAY_LOGGING_CHANNEL=${BIRTHDAY_LOGGING_CHANNEL}
    - COMPANY_NAME=${COMPANY_NAME}
    - CREATE_BIRTHDAY_CHANNELS=${CREATE_BIRTHDAY_CHANNELS}
    - TENOR_API_KEY=${TENOR_API_KEY}
    - TENOR_IMG_LIMIT=${TENOR_IMG_LIMIT}
    - TENOR_SEARCH_TERM=${TENOR_SEARCH_TERM}
    # hubot-pugme
    - PUGS_LIMIT=${PUGS_LIMIT}
    # hubot-redis-brain
    - REDIS_URL=${REDIS_URL}
    volumes:
    - ./packages:/home/hubot/packages
    - ./scripts:/home/hubot/scripts
  redis:
    image: cusdeb/redis:5.0-armhf
    network_mode: "host"
    environment:
    - REDIS_CONF_bind=127.0.0.1
    - REDIS_CONF_port=16379
    # Enable AOF
    - REDIS_CONF_appendonly=yes
    # Disable RDB
    - REDIS_CONF_save=
    - REDIS_CONF_loglevel=notice
    volumes:
    - /srv/redis-dump:/dump

