version: "2"
services:
  redis:
    image: cusdeb/redis:6.0-amd64
    network_mode: "host"
    environment:
    - BIND=${BIND}
    - LOGLEVEL=${LOGLEVEL}
    - PORT=${PORT}
    # Enable AOF
    - REDIS_CONF_appendonly=yes
    # Disable RDB
    - REDIS_CONF_save=
    volumes:
    - /srv/redis-dump:/dump

